# Only for ubuntu / debian linux

---
- hosts: localhost
  become: yes
  become_method: sudo

  vars:
    rabbitmq_login_user: admin
    rabbitmq_login_password: mypassword123
    rabbitmq_ping_exchange: x.ping
    rabbitmq_ping_queue: q.ping 

  tasks:
  - name: Install RabbitMQ public key
    apt_key:
      url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
      state: present

  - name: Add RabbitMQ official repo
    apt_repository:
      repo: deb https://dl.bintray.com/rabbitmq/debian bionic main
      state: present
      filename: rabbitmq

  - name: Add Erlang offical repo
    apt_repository:
      repo: deb https://dl.bintray.com/rabbitmq/debian bionic erlang
      state: present
      filename: erlang

  - name: Update all packages
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: true

  - name: Install RabbitMQ package
    apt:
      name: rabbitmq-server
      update_cache: yes
      install_recommends: yes
      state: present

  - name: Enable RabbitMQ plugins
    rabbitmq_plugin:
      names: rabbitmq_management
      state: enabled

  - name: Start RabbitMQ service
    service:
      name: rabbitmq-server
      state: started
      enabled: yes